#!/usr/bin/env node

var ts = require('typescript');

const compileTypescript = (tsSource) => {
  compilerOptions = {
    target: 'es5',
  };

  var jsSource = ts.transpileModule(tsSource, {
    compilerOptions,
  }).outputText;

  return jsSource;
};

let contents = '';

process.stdin.setEncoding('utf8');
process.stdin.on('data', (data) => {
  contents += data;
});
process.stdin.on('end', () => {
  var ts = compileTypescript(contents);
  console.log(ts);
});
process.stdin.resume();
